org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Memaksa Gradle untuk mengabaikan peringatan diskrepansi level API 33/34 pada flutter_blue_plus
android.suppressUnsupportedCompileSdk=33,34,35,36

android.aarMetadataCheck.enabled=false
configurations.all { resolutionStrategy { force 'androidx.core:core:1.13.1'; force 'androidx.core:core-ktx:1.13.1' } }